identifier: ldh6x5vfe074z18e
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: rm-site-v2
homeFolder: /Users/raulmar/Code/rm-site-v2
distFolder: dist/rm-site-v2
outDir: /Users/raulmar/Code/rm-site-v2/dist/static
handle404: ''
allowErrorCollect: false
